# Generated by Django 4.2.20 on 2025-04-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_screentimeentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentimeentry',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('gaming', 'Gaming'), ('entertainment', 'Entertainment'), ('music', 'Music'), ('break', 'Break')], default='work', max_length=20),
        ),
        migrations.AddField(
            model_name='screentimeentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screentimeentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screentimeentry',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screentimeentry',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
