# Generated by Django 4.2.20 on 2025-04-18 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_screentimeentry_category_screentimeentry_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screentimeentry',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='screentimeentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='screentimeentry',
            index=models.Index(fields=['user', 'end_time'], name='tracker_scr_user_id_0a4e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='screentimeentry',
            index=models.Index(fields=['user', 'start_time'], name='tracker_scr_user_id_e43851_idx'),
        ),
    ]
