# Generated by Django 4.2.20 on 2025-04-18 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_screentimeentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screentimeentry',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='screentimeentry',
            name='tracker_scr_user_id_0a4e9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='screentimeentry',
            name='tracker_scr_user_id_e43851_idx',
        ),
        migrations.RemoveField(
            model_name='screentimeentry',
            name='date',
        ),
        migrations.AlterField(
            model_name='screentimeentry',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('entertainment', 'Entertainment'), ('gaming', 'Gaming'), ('social', 'Social'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screentimeentry',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screentimeentry',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
