# Generated by Django 4.2.20 on 2025-06-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_musicplayer_duration'),
        ('tracker', '0006_alter_screentimeentry_category_stopwatch_note_and_more'),
    ]

    operations = [
    ]
