# Generated by Django 4.2.20 on 2025-06-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20240321'),
        ('tracker', '0007_merge_20250612_2043'),
    ]

    operations = [
    ]
