# Generated by Django 4.2.20 on 2025-06-13 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_merge_0002_auto_20240321_0007_merge_20250612_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentimeentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='screentimeentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='repeat',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=10),
        ),
        migrations.AlterField(
            model_name='musicplayer',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicplayer',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='screentimeentry',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='screentimeentry',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
