# Generated by Django 4.2.20 on 2025-06-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_screentimeentry_category_song_favoritesong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tracker.musicplayer'),
        ),
    ]
