# Generated by Django 4.2.20 on 2025-06-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_favoritesong_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteSong',
        ),
    ]
